import {useState} from 'react';
import {api} from './api';
import {money} from '../store/Shop';
export default function OrderRequests({order,reload,admin=false}){
 const [type,setType]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const requests=order.serviceRequests||[];
 const available=['pending_payment','confirmed','processing'].includes(order.status)?'cancellation':order.paymentStatus==='paid'&&['delivered','cancelled'].includes(order.status)?'refund':null;
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{await api(`/orders/${order.id}/requests`,{method:'POST',body:JSON.stringify({type,reason})});setType('');setReason('');await reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function review(e,request){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{await api(`/admin/orders/${order.id}/requests/${request.id}`,{method:'POST',body:JSON.stringify({decision:f.get('decision'),note:f.get('note'),returnConfirmed:f.get('returnConfirmed')==='on'})});await reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="order-service">{error&&<p className="commerce-error" role="alert">{error}</p>}{requests.map(r=><div className="request-status" key={r.id}><div className="commerce-inline"><strong>{r.type==='refund'?'Refund':'Cancellation'} request</strong><span className="commerce-badge">{r.status}</span></div><p>{r.reason}</p><small>{new Date(r.requestedAt).toLocaleString()}{r.amountPaise!=null&&` · ${money(r.amountPaise/100)}`}</small>{r.note&&<p>Review: {r.note}</p>}{r.type==='refund'&&r.status==='approved'&&<p className="commerce-notice">Approved for processing. Not yet sent to the payment provider. No refund has been issued.</p>}{admin&&r.status==='requested'&&<form className="commerce-form" onSubmit={e=>review(e,r)}><label>Decision<select name="decision"><option value="approved">Approve</option><option value="rejected">Reject</option></select></label><label>Review note<textarea name="note" required minLength={5} maxLength={1000}/></label>{r.type==='refund'&&order.status==='delivered'&&<label><input type="checkbox" name="returnConfirmed"/> Return received or explicitly waived</label>}<button disabled={busy} className="store-pill">Save review</button></form>}</div>)}{!admin&&available&&!requests.some(r=>r.type===available&&r.status!=='rejected')&&!type&&<button onClick={()=>setType(available)} className="request-button">Request {available}</button>}{type&&<form onSubmit={submit} className="commerce-form"><label>Reason for {type}<textarea required minLength={5} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><p className="commerce-note">Requests are reviewed by our team. A request does not confirm cancellation or refund.</p><div className="commerce-inline"><button disabled={busy} className="store-pill">{busy?'Submitting…':'Submit request'}</button><button type="button" disabled={busy} onClick={()=>setType('')}>Keep order</button></div></form>}</div>;
}
