import {Link} from 'react-router-dom';
import {ShieldCheck,CreditCard,RotateCcw,LockKeyhole} from 'lucide-react';
import {useAuth} from './Auth';
import {money} from '../store/Shop';
import OrderRequests from './OrderRequests';
export default function PaymentCenter({orders,reload,admin=false}){
 const {config}=useAuth();const connected=config?.paymentMode!=='disabled'&&!!config?.paymentMode;
 return <section className="payment-center"><div className="payment-gateway"><span className="payment-gateway-icon"><ShieldCheck size={30}/></span><div><span className="shop-kicker">PAYMENT GATEWAY</span><h2>Cashfree Payments</h2><p>{connected?`${config.paymentMode==='sandbox'?'Sandbox testing':'Production checkout'} configured`:'Gateway connection pending'} · INR</p></div><span className="commerce-badge">{connected?config.paymentMode:'Not connected'}</span></div><div className="payment-rules-grid">{[[CreditCard,'Hosted checkout','UPI, cards and other methods are shown by Cashfree when enabled on your merchant account.'],[LockKeyhole,'Verified payment status','A redirect is not proof of payment. Orders are confirmed only after server verification.'],[RotateCcw,'Refund review','Approved requests await provider processing. Approval does not mean money has been returned.']].map(([Icon,title,copy])=><article key={title}><Icon size={24}/><h3>{title}</h3><p>{copy}</p></article>)}</div>{!connected&&<p className="commerce-notice">Live collection is unavailable until the gateway is connected. Local demo orders never charge money.</p>}
 <h3>Payment history</h3><div className="commerce-table-wrap"><table className="commerce-table"><thead><tr><th>Order</th><th>Amount</th><th>Method</th><th>Payment</th><th>Reference</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.id}</td><td>{money(o.totalPaise/100)}</td><td>{o.paymentMethod==='demo'?'Demo · no money collected':o.paymentMethod}</td><td>{o.paymentStatus}</td><td>{o.transactionId||'Not recorded'}</td></tr>)}{!orders.length&&<tr><td colSpan={5}>No payments yet.</td></tr>}</tbody></table></div>
 <h3>{admin?'Cancellation & refund review queue':'Your cancellation & refund requests'}</h3>{orders.filter(o=>o.serviceRequests?.length).map(o=><article className="commerce-panel" key={o.id}><strong>{o.id}</strong><OrderRequests order={o} reload={reload} admin={admin}/></article>)}{!orders.some(o=>o.serviceRequests?.length)&&<p className="commerce-empty">No requests yet. {admin?'Customer requests will appear here.':'Open an order to request cancellation or refund review.'}</p>}<Link to="/policies/returns">View store returns policy →</Link></section>;
}
