import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,Droplets,ShieldCheck,Headphones,Wrench,ShoppingBag,MapPin,PackageCheck,Check,SlidersHorizontal} from 'lucide-react';
import {getCatalog} from '../store/Shop';
import {useAuth} from '../commerce/Auth';
import ShopCard from '../components/ShopCard';
const benefits=[[ShieldCheck,'Made for better water','Membrane systems designed around your everyday needs.'],[Headphones,'Guidance that helps','Find the right system with help from our team.'],[Wrench,'Care beyond checkout','Explore installation, maintenance and replacement services.'],[Droplets,'A solution for every space','Water care for homes, businesses and industry.']];
const questions=[['How do I choose the right water system?','The right system depends on your water source, usage and available space. Browse the collection or contact our team for guidance before ordering.'],['Can I manage my orders online?','Yes. Sign in to your customer account to view orders, saved addresses and available order updates.'],['Where can I find replacement filters?','Explore the replacement products in our store. Check compatibility with your existing system, or ask our team before purchasing.'],['Do you offer installation and maintenance?','Our services page covers installation and ongoing care. Contact the team to confirm availability and charges for your location.']];
export default function Home(){const {config}=useAuth();const [products,setProducts]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [category,setCategory]=useState('All products');
useEffect(()=>{getCatalog().then(setProducts).catch(()=>setError(true)).finally(()=>setLoading(false));},[]);
const categories=['All products',...new Set(products.map(p=>p.category).filter(Boolean))];
const shown=category==='All products'?products:products.filter(p=>p.category===category);
return <div className="smart-home">
<section className="smart-hero"><div className="smart-hero-inner"><div className="smart-hero-copy"><span className="smart-eyebrow">WATER CARE, MADE SIMPLE</span><h1>Good water.<br/>Great living.<br/><em>Every single day.</em></h1><p>Discover the right water purification system for your home, your business and everything in between.</p><div className="smart-hero-actions"><Link to="/products" className="smart-button">Explore water systems <ArrowRight size={18}/></Link><Link to="/contact">Help me choose <ArrowRight size={16}/></Link></div><div className="smart-hero-check"><ShieldCheck size={20}/> Precision filtration. Thoughtful care.</div></div><div className="smart-hero-visual"><img src={config?.slide1Image||'/our-story-kitchen.png'} alt="Fresh drinking water in a modern home kitchen"/><div className="smart-visual-label"><span><Droplets size={25}/></span><div><strong>A little more purity.</strong><p>A lot more peace of mind.</p></div></div><span className="smart-hero-stamp">DESIGNED FOR<br/><b>everyday life</b></span></div></div></section>
<div className="smart-benefit-band">{[[Droplets,'Precision filtration'],[SlidersHorizontal,'Systems for every space'],[Wrench,'Installation & care'],[Headphones,'Expert guidance']].map(([Icon,label])=><div key={label}><Icon size={25}/><span>{label}</span></div>)}</div>
<section className="smart-section smart-why"><div className="smart-heading"><span className="smart-eyebrow">THE MEMBRANEIQ DIFFERENCE</span><h2>Better water. Less to worry about.</h2><p>From choosing your first system to keeping it running beautifully, we’re here to help.</p></div><div className="smart-benefits">{benefits.map(([Icon,title,copy])=><article key={title}><span className="smart-icon"><Icon size={32} strokeWidth={1.5}/></span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className="smart-collection"><div className="smart-section"><div className="smart-heading"><span className="smart-eyebrow">FIND YOUR EVERYDAY ESSENTIAL</span><h2>Your water. Your perfect fit.</h2><p>Explore our water systems and genuine replacement essentials.</p></div><div className="smart-filter-tabs" aria-label="Product categories">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} aria-pressed={category===c}>{c}</button>)}</div>{loading?<p role="status">Loading products…</p>:error?<p role="alert">Unable to load products. <Link to="/products">Try the shop</Link></p>:shown.length?<div className="market-product-grid">{shown.map(p=><ShopCard key={p.id} product={p}/>)}</div>:<p>New products are on their way.</p>}<div className="smart-center"><Link className="smart-button outline" to="/products">Explore the full collection <ArrowRight size={18}/></Link></div></div></section>
<section className="smart-section smart-care"><div className="smart-care-image"><img src="/membrane-pure-water.jpg" alt="Fresh water for everyday living" loading="lazy"/><div><Droplets size={28}/><strong>Care in every drop.</strong></div></div><div><span className="smart-eyebrow">MORE THAN A WATER SYSTEM</span><h2>Good water starts with<br/>a little expert care.</h2><p>Get more from your system with the right advice, timely maintenance and essentials that fit.</p><ul>{['Find a system for your water needs','Explore installation and maintenance','Keep your orders and addresses in one place'].map(t=><li key={t}><Check size={18}/>{t}</li>)}</ul><Link to="/services" className="smart-button">Explore our services <ArrowRight size={18}/></Link></div></section>
<section className="smart-steps"><div className="smart-section"><div className="smart-heading"><h2>A simpler way to better water.</h2><p>Just a few steps from finding your fit to making it yours.</p></div><div className="smart-step-grid">{[[ShoppingBag,'Choose your system','Explore products and find the right fit.'],[MapPin,'Add your address','Tell us where you need your water system.'],[PackageCheck,'Place your order','Review your details and complete checkout.'],[Headphones,'Stay connected','Manage orders and get help from your account.']].map(([Icon,title,copy],i)=><article key={title}><span className="smart-step-number">0{i+1}</span><Icon size={32} strokeWidth={1.5}/><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
<section className="smart-section smart-faq"><div><span className="smart-eyebrow">LET’S CLEAR THINGS UP</span><h2>A few things you<br/>might be wondering.</h2><p>Still have a question? We’re happy to help.</p><Link to="/contact">Talk to our team <ArrowRight size={17}/></Link></div><div>{questions.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
<section className="smart-bottom-cta"><div><h2>Ready for your everyday upgrade?</h2><p>Find your next water system with membraneIQ.</p></div><Link to="/products" className="smart-button">Find my water system <ArrowRight size={18}/></Link></section>
</div>}
