import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {motion,useReducedMotion} from 'framer-motion';
import {ArrowUpRight,ArrowRight,Droplets,ShieldCheck,Wrench,MoveUpRight} from 'lucide-react';
import {getCatalog} from '../store/Shop';
import ShopCard from '../components/ShopCard';
export default function Home(){const [products,setProducts]=useState([]);const [error,setError]=useState(false);const reduced=useReducedMotion();useEffect(()=>{getCatalog().then(setProducts).catch(()=>setError(true));},[]);return <div className="store-home">
<section className="store-hero"><div className="store-hero-copy"><span className="store-label"><span/> SMALL CHANGE. BETTER EVERYDAY.</span><h1>Good water.<br/>Great living<span>.</span></h1><p>Meet your everyday upgrade. Thoughtfully designed water systems that bring purity, simplicity, and a little more peace of mind to your home.</p><div className="store-hero-buttons"><Link className="store-pill" to="/products">Shop the collection <ArrowUpRight size={19}/></Link><Link className="store-text-link" to="/technology">Explore the science <ArrowRight size={16}/></Link></div><div className="store-hero-note"><span>01 — 04</span><span>WATER CARE, REIMAGINED.</span></div></div><div className="store-hero-art"><div className="store-orbit"/><span className="store-art-word">PURE</span><motion.div className="store-floating-photo" animate={reduced?{}:{y:[0,-15,0],rotate:[-5,-2,-5]}} transition={{duration:6,repeat:Infinity,ease:'easeInOut'}}><img src="/membrane-tech.jpg" alt="Membrane water filtration system cutaway"/><span>THE MEMBRANE SERIES <ArrowUpRight size={18}/></span></motion.div><motion.div className="store-float-tag" animate={reduced?{}:{y:[0,12,0]}} transition={{duration:5,repeat:Infinity,ease:'easeInOut'}}><Droplets size={23}/><div>Designed around you.<small>Pure water. Less effort.</small></div></motion.div><span className="store-art-caption">Precision inside.<br/>Possibilities outside.</span></div></section>
<div className="store-trust">{[[ShieldCheck,'Precision membrane technology'],[Wrench,'Care beyond your purchase'],[Droplets,'Made for everyday homes']].map(([Icon,text])=><span key={text}><Icon size={19} strokeWidth={1.5}/>{text}</span>)}</div>
<section className="store-section"><div className="store-section-head"><div><span className="shop-kicker">FIND YOUR EVERYDAY ESSENTIAL</span><h2>A little more pure.<br/>A lot more you.</h2></div><Link className="store-text-link" to="/products">Shop all systems <ArrowUpRight size={19}/></Link></div>{error?<p role="status">Products couldn’t load. Please visit the shop to try again.</p>:<div className="store-product-grid">{products.map((product,index)=><ShopCard key={product.id} product={product} index={index}/>)}</div>}</section>
<section className="store-lifestyle"><img src="/our-story-kitchen.png" alt="A carafe of fresh water in a sunlit kitchen" loading="lazy"/><div><span className="shop-kicker">FEELS RIGHT AT HOME</span><h2>Better habits.<br/>One glass at a time.</h2><p>From the first coffee to the last refill. Make clean water a natural part of the way you live.</p><Link className="store-pill light" to="/about">The AquaPure story <ArrowUpRight size={18}/></Link></div></section>
<section className="store-section store-science"><div><span className="shop-kicker">SMALL DETAILS. BIG DIFFERENCE.</span><h2>There’s good science<br/>behind every drop.</h2><Link className="store-text-link" to="/technology">Get beneath the surface <MoveUpRight size={18}/></Link></div><div className="store-science-list">{[['01','Four thoughtful stages','Sediment, carbon, membrane, and polishing. Each layer has a job to do.'],['02','Made to fit real life','Find the system that fits your space, routine, and water care needs.'],['03','We’re here for the long run','Installation, maintenance, and guidance from one place.']].map(([n,title,text])=><article key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
<section className="store-duo"><Link to="/services"><span className="shop-kicker">KEEP THE GOOD GOING</span><h2>A little care.<br/>A longer life.</h2><span>Explore service options <ArrowUpRight/></span></Link><Link to="/contact"><span className="shop-kicker">LET’S FIND YOUR FIT</span><h2>Questions?<br/>We’re all ears.</h2><span>Talk to our team <ArrowUpRight/></span></Link></section>
</div>}
