import {useState,useEffect} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {useAuth} from '../../commerce/Auth';
import {api} from '../../commerce/api';
import {auth} from '../../firebase/config';
import {money} from '../../store/Shop';
import Orders from '../../commerce/Orders';
import ProductEditor from '../../commerce/ProductEditor';
export default function Dashboard(){const {user,ready,profile,logout,config,error:authError}=useAuth();const navigate=useNavigate();const [tab,setTab]=useState('Overview');const [products,setProducts]=useState([]);const [orders,setOrders]=useState([]);const [customers,setCustomers]=useState([]);const [settings,setSettings]=useState(null);const [merchant,setMerchant]=useState(null);const [editor,setEditor]=useState(false);const [selected,setSelected]=useState(null);const [query,setQuery]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const load=async()=>{const [p,o,c,s,m]=await Promise.all([api('/admin/products'),api('/admin/orders'),api('/admin/customers'),api('/config'),api('/admin/merchant')]);setProducts(p);setOrders(o);setCustomers(c);setSettings(s);setMerchant(m);};useEffect(()=>{if(ready&&!user)navigate('/admin');if(profile?.admin)load().catch(e=>setError(e.message));},[ready,user,profile,navigate]);if(authError)return <div className="commerce-page" role="alert">{authError} <button onClick={()=>window.location.reload()}>Retry</button></div>;if(!ready||!profile)return <div className="commerce-page">Checking administrator access…</div>;if(!profile.admin)return <div className="commerce-page"><h1>Administrator access required.</h1><Link to="/account">Your account</Link></div>;async function saveSettings(e){e.preventDefault();setBusy(true);setError('');try{await api('/admin/settings',{method:'PUT',body:JSON.stringify(settings)});setNotice('Store settings saved.');await load();}catch(e){setError(e.message);}finally{setBusy(false);}}async function exportFeed(){try{const token=await auth.currentUser.getIdToken();const r=await fetch('/api/admin/merchant/export',{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Could not export feed');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='merchant-preview.xml';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e.message);}}return <div className="admin-shell"><aside className="admin-sidebar"><Link to="/" className="store-logo">aquapure.</Link><span>STORE ADMIN</span><nav>{['Overview','Products','Orders','Customers','Google Merchant','Settings'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setNotice('');setEditor(false);}}>{t}</button>)}</nav><Link to="/">View storefront ↗</Link><button onClick={async()=>{await logout();navigate('/admin');}}>Sign out</button></aside><main className="admin-content"><header className="commerce-heading"><div><span className="shop-kicker">{config?.emulator?'FIREBASE EMULATOR · LOCAL DATA':'FIREBASE STORE'}</span><h1>{tab}</h1></div><button disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Refresh</button></header>{error&&<p className="commerce-error" role="alert">{error}</p>}{notice&&<p className="commerce-notice" role="status">{notice}</p>}
{tab==='Overview'&&<><div className="admin-metrics">{[['Products',products.filter(p=>p.status==='active').length],['Orders',orders.length],['Customers',customers.length],['Paid revenue',money(orders.filter(o=>o.paymentStatus==='paid').reduce((n,o)=>n+o.totalPaise/100,0))]].map(([label,v])=><article key={label}><span>{label}</span><strong>{v}</strong></article>)}</div><section className="commerce-panel"><h2>Ready for your products</h2><p>Create drafts, add photos, prices, stock and manufacturer identifiers, then publish when you’re ready. Demo products never enter your Google feed.</p><button className="store-pill" onClick={()=>{setTab('Products');setSelected(null);setEditor(true);}}>Add your first product</button></section><h2>Recent orders</h2><Orders orders={orders.slice(0,5)} reload={load} admin/></>}
{tab==='Products'&&<>{editor?<ProductEditor key={selected?.id||'new'} product={selected} onClose={()=>setEditor(false)} onDone={()=>{setEditor(false);setNotice('Product saved.');load().catch(e=>setError(e.message));}}/>:<><div className="commerce-toolbar"><input placeholder="Search products…" aria-label="Search products" value={query} onChange={e=>setQuery(e.target.value)}/><button className="store-pill" onClick={()=>{setSelected(null);setEditor(true);}}>Add product</button></div><div className="commerce-table-wrap"><table className="commerce-table"><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Status</th><th>Action</th></tr></thead><tbody>{products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).map(p=><tr key={p.id}><td><strong>{p.name}</strong><small>{p.demo?'Demo · ':''}{p.id}</small></td><td>{money(p.price)}</td><td>{p.stock}</td><td><span className="commerce-badge">{p.status}</span></td><td><button onClick={()=>{setSelected(p);setEditor(true);}}>Edit</button></td></tr>)}</tbody></table></div><p className="commerce-note">Archive a product using Edit to remove it from the storefront without losing order records.</p></>}</>}
{tab==='Orders'&&<Orders orders={orders} reload={load} admin/>}
{tab==='Customers'&&<div className="commerce-table-wrap"><table className="commerce-table"><thead><tr><th>Name</th><th>Email</th><th>Joined</th><th>Orders</th></tr></thead><tbody>{customers.map(c=><tr key={c.id}><td>{c.name||'—'}</td><td>{c.email}</td><td>{c.createdAt?new Date(c.createdAt).toLocaleDateString():'—'}</td><td>{orders.filter(o=>o.uid===c.id).length}</td></tr>)}</tbody></table></div>}
{tab==='Google Merchant'&&<><section className="commerce-panel"><h2>Product feed readiness</h2><p>Status: {merchant?.enabled?'Live publication enabled':'Not published'}. A public HTTPS domain, real product photos, valid identifiers, policies and live checkout are needed before submission. Google approval is not automatic.</p><p><code>{merchant?.feedUrl}</code></p><button className="store-pill" onClick={exportFeed}>Download eligible-product XML preview</button><p className="commerce-note">An empty preview means no products currently pass the readiness checks. Add this feed in Merchant Center only after deployment and account verification.</p></section>{merchant?.products.map(p=><article className="commerce-panel" key={p.id}><strong>{p.name}</strong>{p.issues.length?<ul>{p.issues.map(i=><li key={i}>• {i}</li>)}</ul>:<p>Ready for the feed.</p>}</article>)}</>}
{tab==='Settings'&&settings&&<form className="commerce-form commerce-panel" onSubmit={saveSettings}><h2>Business & shipping</h2><div className="commerce-fields">{[['businessName','Business name','text'],['siteUrl','Public store URL (HTTPS)','url'],['supportEmail','Support email','email'],['shippingFee','Flat shipping fee (INR)','number'],['freeShippingAbove','Free shipping threshold (0 = disabled)','number']].map(([k,label,type])=><label key={k}>{label}<input type={type} min={0} step={type==='number'?'0.01':undefined} value={settings[k]} onChange={e=>setSettings({...settings,[k]:e.target.value})}/></label>)}</div><h2>Store policies</h2>{[['shippingPolicy','Shipping & delivery'],['returnsPolicy','Returns & refunds'],['privacyPolicy','Privacy'],['termsPolicy','Terms of service']].map(([k,label])=><label key={k}>{label}<textarea rows={4} value={settings[k]} onChange={e=>setSettings({...settings,[k]:e.target.value})}/></label>)}<label className="commerce-checkbox"><input type="checkbox" checked={settings.merchantLive} onChange={e=>setSettings({...settings,merchantLive:e.target.checked})}/>Publish Google product feed (live setup required)</label><p className="commerce-note">Cashfree: {settings.paymentMode}. Configure provider keys in the server environment, never in this dashboard or frontend.</p><button className="store-pill" disabled={busy}>{busy?'Saving…':'Save settings'}</button></form>}
</main></div>}
